const opportunities = [
  {
    id: 1,
    name: 'United World Colleges',
    href: 'https://www.tj.uwc.org/',
    description:
      'Group of international schools that aims to make education a force to unite peoples, nations, and cultures for peace and a sustainable future.',
    notes: 'English required',
    imageAlt: 'United World Colleges',
    imageSrc: require('./images/UWCLogo.jpeg'),
    category: 'school',
  },
  {
    id: 2,
    name: 'UCA Graduate Summer School',
    href: 'https://ucentralasia.org/schools/school-of-professional-and-continuing-education/continuing-education-programme/spce-tajikistan',
    description:
      'Take summer classes at the presigious UCA Graduate school and learn from the best professors in the country.',
    notes: 'High school seniors',
    imageAlt: 'UCA Graduate Summer School',
    imageSrc: require('./images/randomDude.png'),
    category: 'school',
  },
  {
    id: 3,
    name: 'Media School CABAR Asia',
    href: 'https://school.cabar.asia/en/',
    description: 'Online courses for the youth.',
    notes: 'interest in journalism needed',
    imageAlt: 'Media School CABAR Asia',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 4,
    name: 'Future Leaders Exchange Program(FLEX)',
    href: 'https://tajikistan.americancouncils.org/flex-rn',
    description: 'Exchange Program for Tajik high school students in the U.S.',
    notes: 'Grade 11 only',
    imageAlt: 'Media School CABAR Asia',
    imageSrc: require('AC+Field+Office+Logo_Tajikistan.png'),
    category: 'course',
  },
  {
    id: 5,
    name: 'AKHP Debate Club',
    href: 'https://www.facebook.com/groups/akhpdebateclub/',
    description:
      'Official Facebook page of one of the best debates club in the country',
    notes: 'Anyone with some knowledge of English and Russian',
    imageAlt: 'AKHP',
    imageSrc: require('39193604_2251029375183905_622698222728511488_n.jpeg'),
    category: 'course',
  },
  {
    id: 6,
    name: 'Global UGRAD',
    href: 'https://tj.usembassy.gov/ru/global-undergraduate-exchange-program-2022-2023-ru/',
    description: 'Global Students Exchange Program',
    notes: 'University Students with knowledge of English',
    imageAlt: 'UGRAD',
    imageSrc: require('.dos-logo-light.webp'),
    category: 'course',
  },
  {
    id: 7,
    name: 'Peak Tajikistan',
    href: 'http://peak.tj/',
    description: 'PEAK Enterprise and Innovation Programme',
    notes: 'Opportunities for people with entrepreneurial ideas',
    imageAlt: 'Peak Tajikistan',
    imageSrc: require('./images/peakLogo.jpeg'),
    category: 'course',
  },
  {
    id: 8,
    name: 'TajRupt',
    href: 'https://www.tajrupt.org/',
    description: 'EXTRACURRICULAR RESOURCE CENTER ',
    notes: 'Opportunities to implement your projects as a high school student',
    imageAlt: 'TajRupt',
    imageSrc: require('./images/tajrupt.png'),
    category: 'course',
  },
  {
    id: 9,
    name: 'Nortwestern University',
    href: 'https://www.qatar.northwestern.edu/admissions/undergraduate/pre-university-programs.html',
    description: 'Pre-College Programs for high school students',
    notes: 'Opportunities to gain knowledge in specific fields before college',
    imageAlt: 'Northwestern University',
    imageSrc: require('./images/northwesternUni.jpeg'),
    category: 'course',
  },
  {
    id: 10,
    name: '2022 Central Asian Journalism Summer Institute',
    href: 'https://www.meridian.org/announcement/2022-central-asian-journalism-summer-institute/',
    description:
      'Opportunity for citizens of Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan, or Uzbekistan',
    notes: '18 to 30 years of age on June 13, 2022',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/journalismInstitute.jpeg'),
    category: 'course',
  },
  {
    id: 11,
    name: 'Yale Global Scholars',
    href: 'https://globalscholars.yale.edu/',
    description:
      'Opportunity for talented international high school students to apply',
    notes: 'Yale University',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/YYGS.png'),
    category: 'course',
  },
  {
    id: 12,
    name: 'Y-Peer',
    href: 'http://y-peer.tj/about-us/',
    description:
      'Opportunity for talented international high school students to apply',
    notes: '18 to 30 years of age on June 13, 2022',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/ypeer.jpeg'),
    category: 'course',
  },
  {
    id: 13,
    name: 'Summer Academy, The School of the New York Times',
    href: 'https://nytedu.com/admissions/summer-academy-admissions/',
    description:
      'Educational program that helps high schoolers to understand the world',
    notes: 'high schoolers',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/nytimes.jpeg'),
    category: 'course',
  },
  {
    id: 13,
    name: 'The Ian Parry Scholarship',
    href: 'http://www.ianparry.org/scholarship/',
    description: 'International photographic competition for people under 24',
    notes: 'high schoolers',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/ianParry.png'),
    category: 'course',
  },
  {
    id: 14,
    name: 'Afice exchange program',
    href: 'https://www.afice.org/',
    description: 'Exchange program resembling FLEX',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/afice.jpeg'),
    category: 'exchange program',
  },
  {
    id: 15,
    name: 'OSCE academy',
    href: 'https://osce-academy.net/en/seminars/full/190.html',
    description: 'Summer school program',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/OSCEAcademy.jpeg'),
    category: 'summer school',
  },
  {
    id: 16,
    name: 'Rice University Course',
    href: 'https://visitingowls.rice.edu/request-info?utm_term=%2Bstanford+%2Bsummer+%2Bprogram&utm_campaign=Visiting+Owls+-+CA%2CCT%2CMA%2CNY%2CNC%2CRI&utm_source=adwords&utm_medium=ppc&hsa_acc=4001610170&hsa_cam=11873042367&hsa_grp=116307014358&hsa_ad=487296167426&hsa_src=g&hsa_tgt=kwd-306328807855&hsa_kw=%2Bstanford+%2Bsummer+%2Bprogram&hsa_mt=b&hsa_net=adwords&hsa_ver=3&gclid=Cj0KCQjwpv2TBhDoARIsALBnVnnu4mrH764zKFaNQv1f3-JDvKEcO9PLj-SJBz01tDpXfAmby_x2FlEaAv76EALw_wcB',
    description: 'Summer courses',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/riceUni.jpeg'),
    category: 'course',
  },
  {
    id: 17,
    name: 'UNESCO Prize for Girls’ and Women’s Education',
    href: 'https://en.unesco.org/themes/women-s-and-girls-education/prize/nomination',
    description: 'Online nomination',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/UNESCO.jpeg'),
    category: 'course',
  },
  {
    id: 18,
    name: '1000 girls - 1000 futures',
    href: 'https://www.nyas.org/programs/global-stem-alliance/1000-girls-1000-futures/',
    description: 'An opportunity for women interested in STEM',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/globalStemAlliance.png'),
    category: 'educational opportunity',
  },
]

export default opportunities
