const opportunities = [
  {
    id: 1,
    name: 'United World Colleges',
    href: 'https://www.tj.uwc.org/',
    description:
      'Group of international schools that aims to make education a force to unite peoples, nations, and cultures for peace and a sustainable future.',
    notes: 'English required',
    imageAlt: 'United World Colleges',
    imageSrc: require('./images/UWCLogo.jpeg'),
    category: 'school',
  },
  {
    id: 2,
    name: 'UCA Graduate Summer School',
    href: 'https://ucentralasia.org/schools/school-of-professional-and-continuing-education/continuing-education-programme/spce-tajikistan',
    description:
      'Take summer classes at the presigious UCA Graduate school and learn from the best professors in the country.',
    notes: 'High school seniors',
    imageAlt: 'UCA Graduate Summer School',
    imageSrc: require('./images/randomDude.png'),
    category: 'school',
  },
  {
    id: 3,
    name: 'Media School CABAR Asia',
    href: 'https://school.cabar.asia/en/',
    description: 'Online courses for the youth.',
    notes: 'interest in journalism needed',
    imageAlt: 'Media School CABAR Asia',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 4,
    name: 'Future Leaders Exchange Program(FLEX)',
    href: 'https://tajikistan.americancouncils.org/flex-rn',
    description: 'Exchange Program for Tajik high school students in the U.S.',
    notes: 'Grade 11 only',
    imageAlt: 'Media School CABAR Asia',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 5,
    name: 'AKHP Debate Club',
    href: 'https://www.facebook.com/groups/akhpdebateclub/',
    description:
      'Official Facebook page of one of the best debates club in the country',
    notes: 'Anyone with some knowledge of English and Russian',
    imageAlt: 'AKHP',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 6,
    name: 'Global UGRAD',
    href: 'https://tj.usembassy.gov/ru/global-undergraduate-exchange-program-2022-2023-ru/',
    description: 'Global Students Exchange Program',
    notes: 'University Students with knowledge of English',
    imageAlt: 'UGRAD',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 7,
    name: 'Peak Tajikistan',
    href: 'http://peak.tj/',
    description: 'PEAK Enterprise and Innovation Programme',
    notes: 'Opportunities for people with entrepreneurial ideas',
    imageAlt: 'Peak Tajikistan',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 8,
    name: 'TajRupt',
    href: 'https://www.tajrupt.org/',
    description: 'EXTRACURRICULAR RESOURCE CENTER ',
    notes: 'Opportunities to implement your projects as a high school student',
    imageAlt: 'TajRupt',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 9,
    name: 'Nortwestern University',
    href: 'https://www.qatar.northwestern.edu/admissions/undergraduate/pre-university-programs.html',
    description: 'Pre-College Programs for high school students',
    notes: 'Opportunities to gain knowledge in specific fields before college',
    imageAlt: 'Northwestern University',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 10,
    name: '2022 Central Asian Journalism Summer Institute - Application Open',
    href: 'https://www.meridian.org/announcement/2022-central-asian-journalism-summer-institute/',
    description:
      'Opportunity for citizens of Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan, or Uzbekistan',
    notes: '18 to 30 years of age on June 13, 2022',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 11,
    name: 'Yale Global Scholars',
    href: 'https://globalscholars.yale.edu/',
    description:
      'Opportunity for talented international high school students to apply',
    notes: 'Yale University',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 12,
    name: 'Y-Peer',
    href: 'http://y-peer.tj/about-us/',
    description:
      'Opportunity for talented international high school students to apply',
    notes: '18 to 30 years of age on June 13, 2022',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
  {
    id: 12,
    name: 'Y-Peer',
    href: 'http://y-peer.tj/about-us/',
    description:
      'Opportunity for talented international high school students to apply',
    notes: '18 to 30 years of age on June 13, 2022',
    imageAlt: 'Journalism Summer Institute',
    imageSrc: require('./images/CABAR.jpg'),
    category: 'course',
  },
]

export default opportunities
